/**
 * Build the offline Service Worker from `src/sw/offline-sw.ts` into a single
 * self-contained `public/idb-offline-sw.js`. The output has no import
 * statements left — everything shared with the main-thread fetch handler is
 * inlined via esbuild bundling.
 *
 * `public/idb-offline-sw.js` is committed to git because:
 *   1. The dev server (vite) serves `public/` at the root without running
 *      this build step.
 *   2. End users of the published npm package don't run our build — the
 *      published artefact is `dist/idb-offline-sw.js`, which `build:sw` in
 *      package.json copies from `public/`.
 *
 * Re-run this script whenever `src/sw/offline-sw.ts` or `src/sw/shared.ts`
 * change. `npm run build:sw` does that automatically as part of `npm run build`.
 */

import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..');

await build({
  entryPoints: [path.join(root, 'src/sw/offline-sw.ts')],
  outfile: path.join(root, 'public/idb-offline-sw.js'),
  bundle: true,
  format: 'iife',
  target: 'es2020',
  platform: 'browser',
  // Service Workers run in their own global — no Node APIs available.
  // Keep comments so the output stays reviewable when inspecting via DevTools.
  legalComments: 'inline',
  banner: {
    js: `/**
 * Offline Service Worker for offline map tile serving.
 *
 * Built from src/sw/offline-sw.ts by scripts/build-sw.mjs.
 * DO NOT EDIT THIS FILE BY HAND — changes will be overwritten on next build.
 * Edit src/sw/offline-sw.ts or src/sw/shared.ts instead.
 */`,
  },
  logLevel: 'info',
});

console.log('✓ built public/idb-offline-sw.js');
